import { ASSETS } from "../utils/assets-paths";
import { KEYS } from "../utils/keys";

export const ZOMBIE_TYPES_CONFIG = [
    {
        SPRITE_SHEET_KEY: ASSETS.SPRITESHEETS.ZOMBIE_1.WALK.KEY,

        WALK_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[1].WALK,

        DEATH_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[1].DEATH,

        SCALE: 2.6,
        DEATH_SCALE: 1.6,

        BASE_FRAME_WIDTH: 70,
        BASE_FRAME_HEIGHT: 79,

        HITBOX_WIDTH_RATIO: 0.4,
        HITBOX_HEIGHT_RATIO: 0.6,

        HITBOX_OFFSET_X: 15,
        HITBOX_OFFSET_Y: 27,

        HEAD_HITBOX_RADIUS: 35,
        HEAD_HITBOX_OFFSET_X: 10,
        HEAD_HITBOX_OFFSET_Y: -55,

        SPEED: 150
    },
    {
        SPRITE_SHEET_KEY: ASSETS.SPRITESHEETS.ZOMBIE_2.WALK.KEY,

        WALK_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[2].WALK,

        DEATH_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[2].DEATH,

        SCALE: 1.35,
        DEATH_SCALE: 1.27,

        BASE_FRAME_WIDTH: 131,
        BASE_FRAME_HEIGHT: 156,

        HITBOX_WIDTH_RATIO: 0.5,
        HITBOX_HEIGHT_RATIO: 0.58,

        HITBOX_OFFSET_X: 15,
        HITBOX_OFFSET_Y: 45,

        HEAD_HITBOX_RADIUS: 35,
        HEAD_HITBOX_OFFSET_X: 10,
        HEAD_HITBOX_OFFSET_Y: -55,

        SPEED: 130
    },
    {
        SPRITE_SHEET_KEY: ASSETS.SPRITESHEETS.ZOMBIE_3.WALK.KEY,

        WALK_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[3].WALK,

        DEATH_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[3].DEATH,

        SCALE: 1.6,
        DEATH_SCALE: 1.27,

        BASE_FRAME_WIDTH: 97,
        BASE_FRAME_HEIGHT: 120,

        HITBOX_WIDTH_RATIO: 0.4,
        HITBOX_HEIGHT_RATIO: 0.65,

        HITBOX_OFFSET_X: 25,
        HITBOX_OFFSET_Y: 30,

        HEAD_HITBOX_RADIUS: 30,
        HEAD_HITBOX_OFFSET_X: 0,
        HEAD_HITBOX_OFFSET_Y: -55,

        SPEED: 170
    },
    {
        SPRITE_SHEET_KEY: ASSETS.SPRITESHEETS.ZOMBIE_4.WALK.KEY,

        WALK_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[4].WALK,

        DEATH_ANIM_KEY: KEYS.ANIMATIONS.ZOMBIES[4].DEATH,

        SCALE: 1.3,
        DEATH_SCALE: 1.2,

        BASE_FRAME_WIDTH: 135,
        BASE_FRAME_HEIGHT: 161,

        HITBOX_WIDTH_RATIO: 0.35,
        HITBOX_HEIGHT_RATIO: 0.6,

        HITBOX_OFFSET_X: 25,
        HITBOX_OFFSET_Y: 45,

        HEAD_HITBOX_RADIUS: 35,
        HEAD_HITBOX_OFFSET_X: -20,
        HEAD_HITBOX_OFFSET_Y: -60,

        SPEED: 170
    }
]